name: Merged main branch
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    # PRへのpush毎に動かしたいし、mainにマージされたときも動かしたい
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - run: |
          echo "run test"
          echo "${{ github.ref }}"
          echo "${{ github.event.pull_request.merged }}"

  action:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - run: |
          echo "run action"
