name: Merged main branch
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - run: echo "run test"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          echo "${{ github.ref }}"
          echo "${{ github.event.pull_request.merged }}"
