name: Slack Notification Test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Generate send payload for slack
        uses: litencatt/notion-db-pages-payload-for-slack@v1.0.3
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        with:
          header: Header
          description: Description
          filter: |
            {
              "and: [
                {
                  "property": "Select",
                  "select": {
                    "equals": "Foo"
                  }
                },
                {
                  "property": "Number",
                  "number": {
                    "greater_than_or_equal_to": 3
                  }
                },
                {
                  "property": "Multi-select",
                  "multi_select": {
                    "contains": "AAA"
                  }
                }
              ]
            }
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload-file-path: "./payload.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
